config/routes.rb
JusCollege::Application.routes.draw do
  root 'hotels#index'

  resources :hotels
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base

  has_many :hotel_tags, dependent: :destroy
  has_many :tags, through: :hotel_tags

  validates_presence_of :name
end

app/models/hotel_tag.rb
class HotelTag < ActiveRecord::Base

  belongs_to :tag
  belongs_to :hotel

  validates_presence_of :tag_id
  validates_presence_of :hotel_id
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :hotel_tags, dependent: :destroy
  has_many :hotels, through: :hotel_tags

  before_validation :downcase_name

  validates_presence_of :name

  def downcase_name
    self.name = name.to_s.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find_by(id: params[:id])
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper

  def color_scheme(tag)
    case tag.color_scheme

    when 1
      'danger'
    when 2
      'warning'
    when 3
      'success'
    end
  end

  def star_class(star_number, hotel)
    if hotel.rating.round >= star_number
      'glyphicon-star text-gold'
    else
      'glyphicon-star-empty text-gray-600'
    end
  end
end

app/views/application/index.html.erb
<% content_for :new_comp do %>
        <div class="container-fluid">
                <div class="row">
                        <div class="col-md-4">.col-md-4</div>
                        <div class="col-md-4">.col-md-4</div>
                        <div class="col-md-4">.col-md-4</div>
                </div>
        </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div class="container-fluid hotel-wrapper">
  <div class="row">
    <div class="col-xs-3 col-md-3"></div>
    <div class="col-xs-6 col-md-6">
      <div class="col-xs-4 col-md-3">
        <a href="<%= hotel_path(hotel) %>">
          <%= image_tag hotel.image_address, width: 150, height: 150 %>
        </a>
      </div>
      <div class="col-xs-8 col-md-9">
        <% hotel.tags.each do |tag| %>
          <span class="<%= "label label-#{color_scheme(tag)}" %>"><%= tag.name.capitalize %></span>
        <% end %>

        <div class="row">
          <div class="col-xs-8">
            <h4>
              <%= hotel.name %>
            </h4>
          </div>

          <div class="col-xs-4">
            <h4 class="pull-right">
              <%= "$#{hotel.price}" %>
              <small class="text-gray-650">CAD</small>
            </h4>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <% 1.upto(5) do |i| %>
              <span class="<%= "glyphicon text-lg #{star_class(i, hotel)}" %>" aria-hidden="true"></span>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <span class="glyphicon glyphicon-map-marker text-3xl text-blue-500" aria-hidden="true"></span>
            <span class="text-gray-700 text-sm"><%= hotel.address %></span>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <a href="<%= hotel_path(hotel) %>">
              <button role="button" class="btn btn-primary pull-right">See availability »</button>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-3 col-md-3"></div>
  </div>
</div>

app/views/hotels/index.html.erb
<h1>Hotels#index</h1>

<div class="bootstrap-iso">
  <div class="panel panel-default">
      <div class="panel-body">
        <% @hotels.each do |hotel| %>
          <%= render partial: 'hotel', locals: { hotel: hotel } %>
        </p>
        <% end %>
    </div>
  </div>
</div>

app/views/hotels/show.html.erb
<h1>Hotels#show</h1>


<div class="bootstrap-iso">
  <div class="panel panel-default">
      <div class="panel-body">
      <%= render partial: 'hotel', locals: { hotel: @hotel } %>
    </div>
  </div>
</div>

app/views/layouts/_auto_charge.html.erb
<div id="paymentPlanModal" class="modal" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" aria-hidden="true" data-dismiss="modal" type="button">
          <i class="fa fa-times"></i>
				</button>
				<div class="text-center">
          <img src="<%= image_path("site-logo-#{WEBSITE_KEY}.png") %>" />
				</div>
			</div>
			<div class="modal-body" style="padding:0px;">
        <% if layaway_type == 'myself' %>
            <%= render :partial => 'events/auto_charge_planing_for_layaway_by_my_self' %>
        <% else %>
            <%= render :partial => 'events/auto_charge_planing_for_layaway_with_friends' %>
        <% end %>
			</div>
			<div class="modal-footer">
				<a class="btn btn-default" data-dismiss="modal">Close</a>
			</div>
		</div>
	</div>
</div>

<% content_for :extra_scripts do %>
	<script type="text/javascript">
		$(document).ready(function() {
			$("#btnConfirmPaymentPlan").click(function(){
				$('#paymentPlanModal').modal({backdrop: true});
			});
		}); 
	</script>
<% end %>

app/views/layouts/_collect_passport_information.html.erb
<div ng-if="pp_properties.length">
  <h3 class="heading-title text-center">PASSPORT INFORMATION</h3>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          Are you the individual who is traveling?
          <span class="req">[<i class="fa fa-asterisk"></i>]</span>
          <div class="select-passport-options filters">
            <label><input type="radio" ng-model="is_traveling" onclick="handleClick();" ng-value="true"> YES</label>
            <label><input type="radio" ng-model="is_traveling" onclick="handleClick();" ng-value="false"> NO</label>
          </div>
        </h4>
      </div>
      <div id="collect-passport-container" class="hidden panel-body">
        <div ng-if="is_traveling">
          <p class="red">
            Please fill out your legal information.
          </p>
          <ul>
            <li>Note: The following information must be entered exactly as it appears on your government- issued
              identification. If any of the following information is entered incorrectly, you may not be allowed onto your
              flight or through immigration.
            </li>
            <li>
              Note: Please fill out as much information as possible right now. You can edit this again from your
              profile later.
            </li>
          </ul>
        </div>

        <div ng-if="!is_traveling">
          <p class="red">
            Please fill out the traveler's legal passport identification information.
          </p>
          <ul>
            <li>
              Note: The following information must be entered exactly as it appears on the traveler's government
              -issued identification. If any of the following information is entered incorrectly, he/she may not be allowed
              onto the flight or through immigration.
            </li>
            <li>
              Note: Please fill out as much information as possible right now. The traveler can edit this again from
              your profile later.
            </li>
          </ul>
        </div>
        <%= render :partial => '/passports/passport_property_fields', :locals => {:event => @event} %>
      </div>
    </div>
  </div>
</div>

<% content_for :extra_scripts do %>
    <script type="text/javascript">
      function handleClick(){
          $('#collect-passport-container').removeClass('hidden');
      }
    </script>
<% end %>

app/views/layouts/_colors_variants.html.erb
<link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

<style>
  <% if !IS_PRODUCTION && show_admin_board %>
  .var_color_1 { background-color: <%= VAR_COLORS[:VAR_COLOR_1] %> !important; }
  <% end %>

  body{
    font-family: 'Muli', sans-serif !important;
  }

  .tablesorter-default {
    font-family: 'Muli', sans-serif !important;
  }

  .popover{
    font-family: 'Muli', sans-serif !important;
  }
</style>

app/views/layouts/_credit_card_form.html.erb
<form action="<% if defined?(url) && url %><%= url %><% else %>{{ paymentUrl }}<% end %>"
      method="POST" ng-controller="StripePaymentFormCtrl" ng-submit="submit($event)" id="credit-card-form">

  <input type="hidden" value="<%= session[:_csrf_token]%>" name="authenticity_token" />
  <input type="hidden" value="credit_card" name="payment_method" />
  <input type="hidden" name="to_pay_amount" ng-model="to_pay_amount" value="{{ getToPayAmount() }}" readonly/>

  <%= render :partial => 'layouts/shipping_address' if defined?(@cart) && @cart[:requires_shipping_address] %>

  <div class="form-group text-center" style="margin-top: 2rem">
    <div style="margin-bottom: 2rem">
      <label for="credit_card_name" style="color: #757575">Cardholder name</label>
      <input type="text" class="form-control" style="margin: 0 auto; max-width: 500px; height: 100%" name="credit_card_name" placeholder="Cardholder name" ng-model="name">
    </div>

    <label for="card-element" style="color: #757575">Credit or debit card</label>
    <div id="card-element" class="form-control" style="margin: 0 auto; max-width: 500px; height: 100%">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" class="red" role="alert"></div>
  </div>

  <% confirm_payment_plan = defined?(confirm_payment_plan) && confirm_payment_plan %>
  <%= render :partial => '/layouts/terms_and_privacy_policy', locals: {:confirm_payment_plan => confirm_payment_plan} %>

  <div class="padding-all">
    <h3 style="color: black">
      Unity Travel provides refund protection to all customers at <b>no extra cost to you.</b>
    </h3>

    <p>
      Receive a full refund of your transaction (event, booking fees, payment fees and even our fee!) if you are unable to attend the event due to an unforeseen circumstance. Some scenarios which are covered, but not limited to:
    </p>

    <ul>
      <li> Accident, Injury, Illness </li>
      <li> Pre-existing Medical Conditions </li>
      <li> Adverse Weather </li>
      <li> Scheduled Airline Failure </li>
      <li> Private vehicle failure </li>
      <li> Pregnancy related conditions </li>
      <li> Armed forces &amp; emergency recall </li>
      <li> Redundancy </li>
      <li> Any emergency circumstance </li>
      <li> And many more... </li>
    </ul>

    <p>
      View more information <a href="https://www.refundprotect.me/member-wording" class="light-blue">here</a>
    </p>
  </div>

  <div class="col-sm-12 text-center">
    <button type="submit" class="btn btn-info btn-lg" ng-disabled="isSubmitButtonDisabled">
      <%= defined?(text_button) && text_button ? text_button : 'Place order' %>
      <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i>
    </button>
  </div>
</form>

<%= render :partial => '/layouts/auto_charge', locals: { :layaway_type => layaway_type } if confirm_payment_plan %>

<% content_for :extra_scripts do %>
    <script type="text/javascript">
        $(function(){
          JusCollege.AngularUtils.applyData('[ng-controller=StripePaymentFormCtrl]', 'init', function (scope) {
            <% if defined?(@cart) && @cart[:requires_shipping_address] %>
                scope.update_primary_shipping_address_path = "<%= update_primary_shipping_address_user_path(@current_user.id) %>";
            <% end %>
            <% if confirm_payment_plan %>
                scope.layawayPayments = <%= raw(layawayPayments.to_json) %>;
            <% end %>
          });
        });
    </script>
<% end %>

app/views/layouts/_event_categories.html.erb
<% event_slug = event_slug || nil %>
<div class="event-categories hidden-xs">
  <ul class="nav navbar-nav">
    <% event_categories.each do |category| %>
        <li>
          <a href="<%= event_list_path(:type => category[:id]) %>" class="<%= current_category == category[:id] ? 'active' : '' %>">
            <b><%= category[:name] %></b>
            <span class="small-text">(<%= category[:event_count] %>)</span>
          </a>
        </li>
    <% end %>
  </ul>
  <div class="clear"></div>
  <div class="col-md-12 center"><a href="<%= INQUIRY_URL %>" class="btn btn-info btn-lg btn-block">Create Your Custom Trip</a></div>
</div>

<div class="drop-event-categories visible-xs">
  <label class="dropdown-caret">
    <select>
      <% event_categories.each do |category| %>
          <option <%= 'selected' if current_category == category[:id] %> value="<%= category[:id] %>">
            <%= "#{category[:name]} (#{category[:event_count]})" %>
          </option>
      <% end %>
    </select>
  </label>
  <a href="<%= INQUIRY_URL %>" class="btn btn-info btn-lg btn-block">Create Your Custom Trip</a>
</div>


<% content_for :extra_scripts do %>
    <script>
        $(document).ready(function(){
            $('.drop-event-categories select').change(function(){
                window.location.href = '/event-list?type=' + $(this).val();
            });
        });
    </script>
<% end %>

app/views/layouts/_flight_policy.html.erb
<% flight_policy = StaticPage.friendly.find(StaticPage::PAGES['AIRLINE_BAGGAGE_FEE_POLICY']) %>

<div id="flight_policy_modal" class="modal" style="display: none;">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h3 class="modal-title padding-top"><%= flight_policy ? flight_policy.title : 'Airline Baggage Fee Policy' %></h3>
      </div>
      <div class="modal-body text-left">
        <%= flight_policy.nil? ? 'Content is under construction...' : raw(flight_policy.description) %>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flight_terms.html.erb
<div class="flight-terms">
  <h4>Important:</h4>
  <p>
    You have chosen a JusGo Flight itinerary!
    Selecting a JusGo Flight itinerary allows you to lock in your trip and begin your payments months in advance, without having a definite itinerary.
    By choosing a JusGo Flight Itinerary, you have given us consent to choose multiple flight itineraries from any airport(s) within close proximity of your school or departure city on your real travel dates or package nights.
    You will select your flight from the provided itineraries closer to your travel date.
  </p>
</div>

app/views/layouts/_hotel_policy.html.erb
<% hotel_policy = StaticPage.friendly.find(StaticPage::PAGES['ROOMING_INSTRUCTIONS']) %>

<div id="hotel_policy_modal" class="modal" style="display: none;">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h3 class="modal-title padding-top"><%= hotel_policy ? hotel_policy.title : 'Rooming Instructions' %></h3>
      </div>
      <div class="modal-body text-left">
        <%= hotel_policy.nil? ? 'This page is being built...' : raw(hotel_policy.description) %>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_order.html.erb
<% currency = orders.get_currency %>

<% if orders.present? %>
    <div class="panel panel-default">
      <div>
        <!-- deposit tickets -->
        <% if [Order::ORDER_TYPE['CABO_SPRING_BREAK_DEPOSIT_BOOK']].include?(orders.order_type) %>
            <div class="cart-table">
              <div class="cart-row">
                <div class="cart-cell product-logo hidden-print">
                  <% if orders.event.image_1.blank? %>
                      <img src="<%= s3_image_path('no-product-image-small.jpg') %>" width="150">
                  <% else %>
                      <img src="<%= orders.event.image_1 %>/convert?w=100">
                  <% end %>
                </div>
                <div class="cart-cell product-description" style="width: auto">
                  <div class="heading-title"><%= "#{orders.event.name} (#{number_to_currency(orders.total_price * currency.exchange_rate, unit: currency.symbol)} #{currency.code} deposited)" %></div>
                </div>
                <div class="cart-cell product-price">
                  1 x
                  <span class="heading-title"><%= "#{number_to_currency(orders.total_price * currency.exchange_rate, unit: currency.symbol)} #{currency.code}" %></span>
                </div>
              </div>
            </div>
        <% else %>
            <table class="table">
              <thead>
              <tr>
                <th>Product</th>
                <th class="text-right">Price</th>
                <th class="text-center">Qty</th>
                <th class="text-right">Total</th>
              </tr>
              </thead>
              <% if products.present? %>
                  <% products.each do |product| %>
                      <% if product.class.to_s == 'OrderItem' %>
                          <tr>
                            <td><%= product.order.event.name %></td>
                            <td class="text-right"><%= "#{number_to_currency(product.unit_price * currency.exchange_rate, unit: currency.symbol)} #{currency.code}" %></td>
                            <td class="text-center"><%= product.quantity %></td>
                            <td class="text-right"><%= "#{number_to_currency(product.unit_price * product.quantity * currency.exchange_rate, unit: currency.symbol)} #{currency.code}" %></td>
                          </tr>
                      <% else %>
                          <% product[:sub_items].each_with_index do |sub_item, idx| %>
                              <tr>
                                <% if idx == 0 %>
                                    <td rowspan="<%= product[:sub_items].length %>">
                                      <h4><%= product[:name] %></h4>
                                      <h6><%= product[:subtitle] %></h6>
                                    </td>
                                <% end %>
                                <td class="text-right"><%= "#{number_to_currency(sub_item[:unit_price] * currency.exchange_rate, unit: currency.symbol)} #{currency.code}" %></td>
                                <td class="text-center"><%= sub_item[:quantity] %></td>
                                <td class="text-right"><%= "#{number_to_currency(sub_item[:total_price] * currency.exchange_rate, unit: currency.symbol)} #{currency.code}" %></td>
                              </tr>
                          <% end %>
                      <% end %>
                  <% end %>
              <% end %>
            </table>
        <% end %>
        <div class="center">
          <% if defined? checkout_url %>
              <%= link_to raw("Checkout <i class='fa fa-chevron-right'></i><i class='fa fa-chevron-right'></i>"), checkout_url, :class => 'btn btn-info btn-lg' %>
          <% elsif defined? continue_shopping_url %>
              <%= link_to raw("<i class='fa fa-chevron-left'></i><i class='fa fa-chevron-left'></i> Continue Shopping"), continue_shopping_url, class: "btn btn-default " %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

<% if defined?(cart) && !cart.nil? && cart[:items].length > 0 %>
    <h3 class="heading-title text-center">NEW ITEMS</h3>
    <%= render :partial => '/events/checkout/_cart_table',
               :locals => { cart: cart ,continue_shopping_url: event_products_path(@event.slug), update_action: true} %>
<% end %>

<% if orders != nil %>
    <% paid_amount = orders.paid_amount %>
    <% if paid_amount > 0 %>
        <h3 class="heading-title padding-row">
          <span>Amount Already Paid</span>
          <span class="pull-right"><%= "#{number_to_currency(paid_amount * currency.exchange_rate, unit: currency.symbol)} #{currency.code}" %></span>
        </h3>
    <% end %>

    <h3 class="heading-title padding-row">
      <span>Total Remaining</span>
      <span class="pull-right">
        <% remaining_amount = orders.remaining_amount %>
        <% if @cart.nil? %>
            <%= "#{number_to_currency(remaining_amount * currency.exchange_rate, unit: currency.symbol)} #{currency.code}" %>
        <% else %>
            <%= "#{number_to_currency((remaining_amount + @cart[:total_price]) * currency.exchange_rate, unit: currency.symbol)} #{currency.code}" %>
        <% end %>
      </span>
    </h3>
<% end %>

app/views/layouts/_page_size_selector.html.erb
<% if total_entries > MIN_PAGE_SIZE %>
    <span class="page-size-title">Page Size:</span>
    <%= select_tag page_size_name + '_page_size_selector',
                   options_for_select([[MIN_PAGE_SIZE, MIN_PAGE_SIZE], [25, 25], [50, 50], [100, 100]],
                                      page_size_value),
                   :class => 'page-size-combobox',
                   'page-size-name' => page_size_name,
                   'other-params' => defined?(other_params) ? other_params.to_json : '' %>

    <% if is_render_script %>
        <% content_for :extra_scripts do %>
            <script>
                $('html').off('change', '.page-size-combobox').on('change', '.page-size-combobox', function () {
                    $('.modal-backdrop').remove();
                    var page_size_name = $(this).attr('page-size-name') + "_per_page";
                    var other_params = $.trim($(this).attr('other-params'));
                    var cookie_value = getCookie(page_size_name);

                    if (cookie_value != $(this).val()) {
                        setCookie(page_size_name, $(this).val(), 1);
                        var url = window.location.pathname;
                        if (other_params != '') {
                            other_params = jQuery.parseJSON(other_params);
                            if (other_params && other_params.length > 0) {
                                $.each(other_params, function (i, p) {
                                    url += i == 0 ? '?' : '&';
                                    url += p.name + '=' + p.value;
                                });
                            }
                        }
                        wiselinks.load(url);
                    }
                });
            </script>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/_payment_phone.html.erb
<div class="form-group col-sm-6 padding-top">
    <label for="phone" style="color: #757575">Mobile Phone Number <small><b>(used for important &amp; urgent messaging)</b></small></label>
    <input id="phone" class="col-sm-4" maxlength="14" type="tel" ng-model="phone" autocomplete="phone" required>
</div>

<% content_for :extra_scripts do %>
    <script type="text/javascript">
        $(document).ready(function() {
            Inputmask({mask: "999-999-9999", clearMaskOnLostFocus: true, autoUnmask: true, greedy: false }).mask($('input[type="tel"]'));
        });
    </script>
<% end %>

app/views/layouts/_shipping_address.html.erb
<h3 class="heading-title text-center">Shipping Address</h3>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">Shipping Address</h4>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-6">
        <label>First Name <span class="req"></span></label>
        <input name="shipping_address_first_name" type="text" maxlength="50" required>
      </div>
      <div class="col-sm-6">
        <label>Last Name <span class="req"></span></label>
        <input name="shipping_address_last_name" type="text" maxlength="50" required>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 padding-top">
        <label>Address <span class="req"></span></label>
        <input name="shipping_address_line_1" type="text" maxlength="50" required>
      </div>
      <div class="col-sm-6 padding-top">
        <label>Address Line 2 <small>(optional)</small></label>
        <input name="shipping_address_line_2" type="text" maxlength="20">
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 padding-top">
        <label>City <span class="req"></span></label>
        <input name="shipping_address_city" type="text" maxlength="50" required>
      </div>
      <div class="col-sm-6 padding-top">
        <label>Zip/Postal Code <span class="req"></span></label>
        <input name="shipping_address_zip" type="text" maxlength="20" required>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 padding-top">
        <label>State / Province <span class="req"></span></label>
        <select name="shipping_address_state" class="select required" id="state" required>
        </select>
      </div>
      <div class="col-sm-6 padding-top">
        <label>Country <span class="req"></span></label>
        <select name="shipping_address_country" class="select required" id="country" required>
          <option value="3">Canada</option>
          <option value="1">United States</option>
        </select>
      </div>
    </div>
  </div>
</div>

<%= render :partial => 'layouts/scripts/country_state_script_easy', :locals => { :state_selector => '#state', :country_selector => '#country' } %>

app/views/layouts/footer/_footer.html.erb
<div id="footer" class="hidden-print">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-12 first-col">
        <%= image_tag "site-logo-gray-#{WEBSITE_KEY}.png" %>
        <br />
        <br class="hidden-xs hidden-sm" />
        © <%= Time.now.strftime('%Y') %>, <%= COMPANY_OFFICIAL_NAME %>.
        <br class="hidden-xs hidden-sm" />
        All rights reserved
      </div>
      <div class="col-md-6 left-right-border visible-md visible-lg col-padding" style="min-height: 200px;">
        <div class="col-sm-6">
          <% StaticPage.contact_pages.each do |page| %>
              <%= link_to page.title, "/#{page.slug}", :class => 'group-title' %>
          <% end %>

          <% StaticPage.boring_stuff_pages.each do |page| %>
              <%= link_to page.title, "/#{page.slug}", :class => 'group-title' %>
          <% end %>
        </div>
        <div class="col-sm-6">
          <% StaticPage.cool_stuff_pages.each do |page| %>
              <%= link_to page.title, "/#{page.slug}" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-3 col-padding visible-md visible-lg">
        <div class="group-title">FOLLOW US</div>
        <br />

        <a class="facebook-icon" target="_blank" href="<%= SOCIAL_LINK[:FACEBOOK] %>" title="Facebook">
          <i class="fa fa-facebook fa-lg"></i> Facebook
        </a>

        <a class="instagram-icon" target="_blank" href="<%= SOCIAL_LINK[:INSTAGRAM] %>" title="Instagram">
          <i class="fa fa-instagram fa-lg"></i> Instagram
        </a>

        <a class="twitter-icon" target="_blank" href="<%= SOCIAL_LINK[:TWITTER] %>" title="Twitter">
          <i class="fa fa-twitter fa-lg"></i> Twitter
        </a>

        <a class="snapchat-icon" target="_blank" href="<%= SOCIAL_LINK[:SNAPCHAT] %>" title="Snapchat">
          <i class="fa fa-snapchat-ghost fa-lg"></i> Snapchat
        </a>
      </div>
    </div>

  </div>
</div>

app/views/layouts/footer/_print_view_footer.html.erb
<div class="page-footer-print visible-print">
  <div style="display: inline-block;">
    © <%= Time.now.strftime('%Y') %>, <%= COMPANY_NAME %> Inc.
    <br />
    All rights reserved
  </div>

  <div class="pull-right">
    <i class="fa fa-envelope-o"></i> <%= EMAIL_ADDRESS[:CONTACT] %>
    <br />
    <i class="fa fa-lg fa-phone"></i> <%= CONTACT_PHONE %>
  </div>
</div>

app/views/layouts/header/_admin_layout.html.erb
<div id="wpwrap">
  <div id="adminmenumain" class="hidden-print var_color_1" role="navigation" aria-label="Main menu">
    <div id="adminmenuback" class="var_color_1"></div>
    <div id="adminmenuwrap">
      <ul id="adminmenu" class="var_color_1">
        <%= render 'layouts/admin_links' %>
      </ul>
    </div>
  </div>
  <div id="wpcontent">
    <div id="wpadminbar" class="hidden-print nojq nojs var_color_1">
      <%= render 'layouts/admin_bar' %>
    </div>
    <div id="wpbody" role="main">
      <div id="wpbody-content">
        <%= render 'layouts/error' %>
        <div class="wrap" id="yield_container">
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

<% content_for :extra_scripts do %>
    <%= render :partial => 'layouts/scripts/admin_script' %>
<% end %>

app/views/layouts/header/_non_admin_layout.html.erb
<div class="row row-offcanvas row-offcanvas-right">

  <%= render 'layouts/header/non_admin_header' if show_header %>

  <%= render 'layouts/error' %>

  <div id="yield_container"><%= yield %></div>

  <%= render 'layouts/footer/footer' if show_footer %>

  <%= render 'layouts/header/side_bar' if show_header %>
</div>